mac80211: add flush_sta method
compile error: backports-5.10.42-1/drivers/net/wireless/ath/ath10k/mac.c:9324:2: error: unknown field 'flush_sta' specified in initializer
  .flush_sta   = ath10k_flush_sta,
  ^

https://github.com/torvalds/linux/commit/d00800a289c9349bb659a698cbd7bc04521dc927

Fixes: Commit 7bf7569 (mac80211: Improve ath10k flush queue mechanism)